
 name: CI

 on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

 jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (main branch)
        uses: actions/checkout@v4

      - name: Checkout code from master
        run: |
          git fetch origin master
          git checkout master

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install all necessary libraries
        run: |
          pip install requests beautifulsoup4 selenium datetime chromedriver  
          pip install pandas 
      - name: Check if the file exists
        run: ls -la
      
      - name: Install dependencies
        run: |
          #pip install --upgrade pip
          #pip install -r requirements.txt  # If there is a dependency file

      - name: Run Python script
        run: python by_scraper_kh_apartments.py
