
 name: CI

 on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

 jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторію (гілка main)
        uses: actions/checkout@v4

      - name: Checkout коду з master
        run: |
          git fetch origin master
          git checkout master

      - name: Встановити Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Встановити всі необхідні бібліотеки
        run: |
          pip install requests beautifulsoup4 selenium datetime chromedriver ssl 
          pip install closing By webdriver timedelta date
      - name: Перевірити, чи є файл
        run: ls -la
      
      - name: Встановити залежності
        run: |
          #pip install --upgrade pip
          #pip install -r requirements.txt  # Якщо є файл із залежностями


      - name: Запустити Python-скрипт
        run: python by_scraper_kh_apartments.py
